openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.care Pods API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.care-pods
  description: null
paths:
  /v2/care-pods:
    get:
      summary: get-care-pods
      description: ''
      tags:
      - grdn.routes.impl.care-pods
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: getV2CarePods
      x-operation-id-source: derived
