openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.macros API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.macros
  description: Simple CRUD operations for macros.
paths:
  /v2/macro:
    get:
      summary: get-macro-handler
      description: Returns all macros
      tags:
      - grdn.routes.impl.macros
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    title:
                      type: string
                    text:
                      type: string
                  required:
                  - id
                  - title
                  - text
      operationId: getV2Macro
      x-operation-id-source: derived
    post:
      summary: post-macro-handler
      description: Creates a new macro.
      tags:
      - grdn.routes.impl.macros
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  title:
                    type: string
                  text:
                    type: string
                required:
                - id
                - title
                - text
                title: grdn.specs.macros/post-macro-response
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
              required:
              - title
              - text
              title: grdn.specs.macros/post-macro-params
        description: 'origin spec: grdn.specs.macros/post-macro-params'
      operationId: postV2Macro
      x-operation-id-source: derived
  /v2/macro/{macro-id}:
    put:
      summary: put-macro-handler
      description: Updates the given macro
      tags:
      - grdn.routes.impl.macros
      parameters:
      - in: path
        name: macro-id
        description: 'origin spec: grdn.specs.macros/put-macro-params'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                text:
                  type: string
              required:
              - title
              - text
              title: grdn.specs.macros/put-macro-params
        description: 'origin spec: grdn.specs.macros/put-macro-params'
      operationId: putV2MacroByMacroId
      x-operation-id-source: derived
    delete:
      summary: delete-macro-handler
      description: Deletes the given macro
      tags:
      - grdn.routes.impl.macros
      parameters:
      - in: path
        name: macro-id
        description: 'origin spec: grdn.specs.macros/delete-macro-params'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: deleteV2MacroByMacroId
      x-operation-id-source: derived
