swagger: '2.0'
info:
  version: null
  title: Grdn grdn.handler grdn.routes.impl.bug API
  description: Eden Health Inc. primary backend API service.
consumes:
- application/json
produces:
- application/json
tags:
- name: grdn.routes.impl.bug
  description: Bug Report handler
paths:
  /v2/bug:
    post:
      summary: report-bug
      description: "Reports a bug.\n   Processes media attachment first. On success, sends email to techsupport\n   and sends PagerDuty alert to on call engineer if appropriate."
      tags:
      - grdn.routes.impl.bug
      parameters:
      - in: body
        name: grdn.specs.bug/create-bug-report-params
        description: 'origin spec: grdn.specs.bug/create-bug-report-params'
        schema:
          type: object
          properties:
            app-version:
              type: string
            chrome-version:
              type: string
            description:
              type: string
              allowEmptyValue: true
            reporter-email:
              type: string
            urgency:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                description:
                  type: string
                  allowEmptyValue: true
                value:
                  type: string
              required:
              - id
              - description
              - value
              title: grdn.specs.bug/urgency
            reporter-athena-id:
              type: integer
              format: int64
            reporter-name:
              type: string
          required:
          - app-version
          - chrome-version
          - description
          - reporter-email
          - urgency
          title: grdn.specs.bug/create-bug-report-params
      responses:
        default:
          description: Default success response.
          schema: {}
