openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.feedback API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.feedback
  description: Contains handlers for routes related to Appointments, Cases, Encounters etc.
paths:
  /v2/case/{case-id}/feedback:
    post:
      summary: case-feedback-handler
      description: Creates a requested feedback entry for a given patient case.
      tags:
      - grdn.routes.impl.feedback
      parameters:
      - in: path
        name: case-id
        description: 'origin spec: grdn.specs.feedback/case-feedback-handler-params'
        required: true
        schema:
          type: number
          format: double
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: object
                    properties:
                      type-id:
                        type: string
                      patient-id:
                        type: string
                        format: uuid
                      id:
                        type: string
                        format: uuid
                        x-anyOf:
                        - type: string
                          format: uuid
                        - type: number
                          format: double
                      updated-at: {}
                      submitted-at: {}
                      status:
                        type: string
                      created-at: {}
                      type:
                        enum:
                        - case
                        - appointment
                        - pediatrics
                        type: string
                      mrn:
                        type:
                        - number
                        - 'null'
                        format: double
                      comment:
                        type:
                        - string
                        - 'null'
                      rating:
                        type:
                        - number
                        - 'null'
                        format: double
                    required:
                    - patient-id
                    - type
                    - type-id
                    - mrn
                    - updated-at
                    - status
                    - submitted-at
                    - id
                    - comment
                    - created-at
                    - rating
                    title: grdn.specs.feedback/feedback
                  event:
                    type: object
                    properties:
                      provider-id:
                        type:
                        - string
                        - 'null'
                        format: uuid
                      patient-id:
                        type:
                        - string
                        - 'null'
                        format: uuid
                      id:
                        type: string
                        format: uuid
                      ops-user-id:
                        type:
                        - string
                        - 'null'
                        format: uuid
                      updated-at: {}
                      event-group:
                        type: string
                      event-data:
                        type: object
                      created-at: {}
                      event-name:
                        type: string
                    required:
                    - id
                    - created-at
                    - updated-at
                    - event-data
                    - event-group
                    - event-name
                    - ops-user-id
                    - provider-id
                    - patient-id
                    title: grdn.specs.event/event
                required:
                - feedback
                - event
                title: grdn.specs.feedback/case-feedback-handler-response
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient-id:
                  type: string
                  format: uuid
              required:
              - patient-id
              title: grdn.specs.feedback/case-feedback-handler-params
        description: 'origin spec: grdn.specs.feedback/case-feedback-handler-params'
      operationId: postV2CaseByCaseIdFeedback
      x-operation-id-source: derived
  /v2/feedback:
    post:
      summary: send-feedback-handler
      description: Sends feedback to all patients with a recent visit
      tags:
      - grdn.routes.impl.feedback
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: postV2Feedback
      x-operation-id-source: derived
  /v2/patient/{patient-id}/feedback:
    get:
      summary: get-feedback-handler
      description: Gets requested feedback survey for a patient
      tags:
      - grdn.routes.impl.feedback
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs/patient-id-params'
        required: true
        schema:
          type: string
          format: uuid
      - in: query
        name: funnel-id
        description: 'origin spec: grdn.specs/patient-id-params'
        required: false
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  date:
                    type: string
                    x-allOf:
                    - type: string
                    - {}
                  department-id:
                    type: string
                    x-anyOf:
                    - type: string
                    - type: integer
                      format: int64
                  feedback-id:
                    type: string
                    format: uuid
                    x-anyOf:
                    - type: string
                      format: uuid
                    - type: number
                      format: double
                  email:
                    type:
                    - string
                    - 'null'
                    x-allOf:
                    - type: string
                    - {}
                  feedback-reasons:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          x-anyOf:
                          - type: string
                            format: uuid
                          - type: number
                            format: double
                        label:
                          type: string
                        created-at: {}
                        updated-at: {}
                        department-id:
                          type: string
                          x-anyOf:
                          - type: string
                          - type: integer
                            format: int64
                      required:
                      - id
                      - label
                      - created-at
                      - updated-at
                      - department-id
                      title: grdn.specs.feedback/feedback-reason
                  type:
                    enum:
                    - case
                    - appointment
                    - pediatrics
                    type: string
                  type-id:
                    type: string
                required:
                - date
                - department-id
                - feedback-id
                - email
                - feedback-reasons
                - type
                - type-id
                title: grdn.specs.feedback/get-feedback-handler-response
      operationId: getV2PatientByPatientIdFeedback
      x-operation-id-source: derived
    put:
      summary: submit-feedback-handler
      description: Write patient feedback to db and send low rating alert if needed.
      tags:
      - grdn.routes.impl.feedback
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs.feedback/submit-feedback-handler-params'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  feedback:
                    type: number
                    format: double
                  reasons:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          x-anyOf:
                          - type: string
                            format: uuid
                          - type: number
                            format: double
                        created-at: {}
                        updated-at: {}
                        patient-feedback-id:
                          type: string
                          format: uuid
                        patient-feedback-reason-id:
                          type: string
                          format: uuid
                      required:
                      - id
                      - created-at
                      - updated-at
                      - patient-feedback-id
                      - patient-feedback-reason-id
                      title: grdn.specs.feedback/reason
                  event:
                    type: object
                    properties:
                      provider-id:
                        type:
                        - string
                        - 'null'
                        format: uuid
                      patient-id:
                        type:
                        - string
                        - 'null'
                        format: uuid
                      id:
                        type: string
                        format: uuid
                      ops-user-id:
                        type:
                        - string
                        - 'null'
                        format: uuid
                      updated-at: {}
                      event-group:
                        type: string
                      event-data:
                        type: object
                      created-at: {}
                      event-name:
                        type: string
                    required:
                    - id
                    - created-at
                    - updated-at
                    - event-data
                    - event-group
                    - event-name
                    - ops-user-id
                    - provider-id
                    - patient-id
                    title: grdn.specs.event/event
                required:
                - feedback
                - reasons
                - event
                title: grdn.specs.feedback/submit-feedback-handler-response
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                feedback-id:
                  type: string
                  format: uuid
                  x-anyOf:
                  - type: string
                    format: uuid
                  - type: number
                    format: double
                comment:
                  type: string
                  allowEmptyValue: true
                deescalation-answer:
                  type: string
                  allowEmptyValue: true
                rating:
                  type: number
                  format: double
                  allowEmptyValue: true
                reason-ids:
                  type: array
                  items:
                    type: string
                    format: uuid
              required:
              - feedback-id
              title: grdn.specs.feedback/submit-feedback-handler-params
        description: 'origin spec: grdn.specs.feedback/submit-feedback-handler-params'
      operationId: putV2PatientByPatientIdFeedback
      x-operation-id-source: derived
