openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.auth API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.auth
  description: Direct authentication handlers
paths:
  /v2/auth:
    get:
      summary: auth-handler
      description: 'Tries to return a sendbird access token for a user. To do this,

        we figure out what a user''s sendbird-user-id in postgres,

        and we ask sendbird for a token. If no active ones exist, we

        create one.'
      tags:
      - grdn.routes.impl.auth
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sendbird-user-id:
                    type: string
                    format: uuid
                  sendbird-session-token:
                    type: string
                required:
                - sendbird-user-id
                - sendbird-session-token
                title: grdn.specs.auth/auth-response
      operationId: getV2Auth
      x-operation-id-source: derived
  /v2/launchdarkly-creds:
    get:
      summary: get-launchdarkly-creds
      description: 'Returns the one-way-hashed provider ID and the signed

        LD hash of that to use as js-secure-mode LD credentials

        without revealing any of our data/ids to LD.'
      tags:
      - grdn.routes.impl.auth
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: getV2LaunchdarklyCreds
      x-operation-id-source: derived
