openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.configuration API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.configuration
  description: null
paths:
  /v2/configuration:
    get:
      summary: get-for-current-user
      description: 'Get configuration specific to authenticated user. Currently simply returns the LD feature flags already

        retrieved by the `wrap-v2-auth` middleware.'
      tags:
      - grdn.routes.impl.configuration
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  feature-flags:
                    type: object
                required:
                - feature-flags
                title: grdn.specs/get-configuration
      operationId: getV2Configuration
      x-operation-id-source: derived
