openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.consent API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.consent
  description: null
paths:
  /v2/patient/{patient-id}/consent:
    get:
      summary: get-patient-consent
      description: 'Given a consent name, depending on feature flags, gets latest version of the consent form or the

        sponsor-specific covid consent version.'
      tags:
      - grdn.routes.impl.consent
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs.consent/get-patient-consent-params'
        required: true
        schema:
          type: string
          format: uuid
      - in: query
        name: name
        description: 'origin spec: grdn.specs.consent/get-patient-consent-params'
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  name:
                    type: string
                  version:
                    type: string
                  url:
                    type: string
                  patient-id:
                    type:
                    - string
                    - 'null'
                    format: uuid
                  consented-at: {}
                  expires-at: {}
                required:
                - id
                - name
                - version
                - url
                - patient-id
                - consented-at
                title: grdn.specs.consent/consent
      operationId: getV2PatientByPatientIdConsent
      x-operation-id-source: derived
    post:
      summary: accept-patient-consent
      description: ''
      tags:
      - grdn.routes.impl.consent
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs.consent/accept-patient-consent-params'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: array
                maxItems: 0
                minItems: 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                consent-id:
                  type: string
                  format: uuid
              required:
              - consent-id
              title: grdn.specs.consent/accept-patient-consent-params
        description: 'origin spec: grdn.specs.consent/accept-patient-consent-params'
      operationId: postV2PatientByPatientIdConsent
      x-operation-id-source: derived
  /v2/patient/{patient-id}/expired-consents:
    get:
      summary: get-expired-consents
      description: 'Given a patient ID, gets each most recently expired consent that does not have a non-expired consent

        for that consent ID.


        As COVID consents are the only type of consent where the expected version for each patient depends

        on their sponsor (as determined by the `sponsor-covid-consent-version` feature flag), COVID consents

        are handled separately with specific logic detailed in APP-7188.'
      tags:
      - grdn.routes.impl.consent
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs.consent/get-expired-consents-params'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    version:
                      type: string
                    url:
                      type: string
                    patient-id:
                      type:
                      - string
                      - 'null'
                      format: uuid
                    consented-at: {}
                    expires-at: {}
                  required:
                  - id
                  - name
                  - version
                  - url
                  - patient-id
                  - consented-at
                  title: grdn.specs.consent/consent
      operationId: getV2PatientByPatientIdExpiredConsents
      x-operation-id-source: derived
