openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.next Step API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.next-step
  description: Contains handlers for routes related to Patients.
paths:
  /v2/next-steps:
    post:
      summary: create-next-step-handler
      description: ''
      tags:
      - grdn.routes.impl.next-step
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                due-date:
                  type: string
                visit-reason-id:
                  type: integer
                  format: int64
                provider-id:
                  type: integer
                  format: int64
                  x-anyOf:
                  - type: integer
                    format: int64
                  - type: string
                in-person-only:
                  type: boolean
                patient-id:
                  type: string
                  format: uuid
                note:
                  type: string
                send-date:
                  type: string
                title:
                  type: string
                type:
                  type: string
                with-provider-id:
                  type: string
                  format: uuid
                  allowEmptyValue: true
              required:
              - patient-id
              - type
              title: grdn.specs.patients/create-next-step-handler-spec
        description: 'origin spec: grdn.specs.patients/create-next-step-handler-spec'
      operationId: postV2NextSteps
      x-operation-id-source: derived
  /v2/next-steps/{next-step-id}:
    put:
      summary: edit-next-step-handler
      description: ''
      tags:
      - grdn.routes.impl.next-step
      parameters:
      - in: path
        name: next-step-id
        description: 'origin spec: grdn.specs.patients/edit-next-step-handler-spec'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                due-date:
                  type: string
                visit-reason-id:
                  type: integer
                  format: int64
                in-person-only:
                  type: boolean
                note:
                  type: string
                send-date:
                  type: string
                title:
                  type: string
                type:
                  type: string
                with-provider-id:
                  type: string
                  format: uuid
                  allowEmptyValue: true
              title: grdn.specs.patients/edit-next-step-handler-spec
        description: 'origin spec: grdn.specs.patients/edit-next-step-handler-spec'
      operationId: putV2NextStepsByNextStepId
      x-operation-id-source: derived
  /v2/patient/{patient-id}/next-steps:
    get:
      summary: get-next-steps-handler
      description: Gets next steps for patient. Calls Athena for Quality Measures and upcoming Appts.
      tags:
      - grdn.routes.impl.next-step
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: '
        required: true
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: getV2PatientByPatientIdNextSteps
      x-operation-id-source: derived
  /v2/patient/{patient-id}/next-steps/{next-step-id}:
    post:
      summary: respond-next-step-handler
      description: Respond to a next step
      tags:
      - grdn.routes.impl.next-step
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: '
        required: true
      - in: path
        name: next-step-id
        description: 'origin spec: '
        required: true
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  next-step-id:
                    type: string
                    format: uuid
                  reply-type:
                    type: string
                  decline-reason-type:
                    type: string
                  decline-detail:
                    type: string
                  resolved-month:
                    type: string
                  delete-reason-type:
                    type: string
                required:
                - next-step-id
                title: grdn.specs.patients/respond-next-step-handler-response
      operationId: postV2PatientByPatientIdNextStepsByNextStepId
      x-operation-id-source: derived
