openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.video Visit API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.video-visit
  description: Handlers for getting and creating Video Visits.
paths:
  /v2/video-visit:
    post:
      summary: create-video-visit
      description: 'Creates a video visit record and sends a message requesting a video visit booking

        to the patient. Does not book an appointment in Athena or schedule a video meeting

        in zoom. Those actions are performed after this resource is created.'
      tags:
      - grdn.routes.impl.video-visit
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient-id:
                  type: string
                  format: uuid
                appointment-reason-id:
                  type: number
                  format: double
                  allowEmptyValue: true
              required:
              - patient-id
              title: grdn.specs.video-visit/create-video-visit-params
        description: 'origin spec: grdn.specs.video-visit/create-video-visit-params'
      operationId: postV2VideoVisit
      x-operation-id-source: derived
    get:
      summary: get-video-visit
      description: Gets a video visit record from postgres.
      tags:
      - grdn.routes.impl.video-visit
      parameters:
      - in: query
        name: video-visit-id
        description: 'origin spec: grdn.specs.video-visit/get-video-visit-params'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  created_at: {}
                  updated_at: {}
                  patient_id:
                    type: string
                    format: uuid
                  appointment_id:
                    type:
                    - number
                    - 'null'
                    format: double
                required:
                - id
                - created_at
                - updated_at
                - patient_id
                - appointment_id
                title: grdn.specs.video-visit/get-video-visit-response
      operationId: getV2VideoVisit
      x-operation-id-source: derived
