openapi: 3.2.0
info:
  version: null
  title: Grdn.handler API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.handler
  description: Configures routes, handlers, and global middleware.
paths:
  /swagger.json:
    get:
      summary: swagger-handler
      description: ''
      tags:
      - grdn.handler
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: getSwaggerJson
      x-operation-id-source: derived
