swagger: '2.0'
info:
  version: null
  title: Grdn grdn.handler grdn.routes.impl.auth API
  description: Eden Health Inc. primary backend API service.
consumes:
- application/json
produces:
- application/json
tags:
- name: grdn.routes.impl.auth
  description: Direct authentication handlers
paths:
  /v2/auth:
    get:
      summary: auth-handler
      description: "Tries to return a sendbird access token for a user. To do this,\n   we figure out what a user's sendbird-user-id in postgres,\n   and we ask sendbird for a token. If no active ones exist, we\n   create one."
      tags:
      - grdn.routes.impl.auth
      parameters: []
      responses:
        default:
          description: Default success response.
          schema:
            type: object
            properties:
              sendbird-user-id:
                type: string
                format: uuid
              sendbird-session-token:
                type: string
            required:
            - sendbird-user-id
            - sendbird-session-token
            title: grdn.specs.auth/auth-response
  /v2/launchdarkly-creds:
    get:
      summary: get-launchdarkly-creds
      description: "Returns the one-way-hashed provider ID and the signed\n   LD hash of that to use as js-secure-mode LD credentials\n   without revealing any of our data/ids to LD."
      tags:
      - grdn.routes.impl.auth
      parameters: []
      responses:
        default:
          description: Default success response.
          schema: {}
