openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.screeners API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.screeners
  description: Handlers for screener fetching and submission.
paths:
  /v2/patient/{patient-id}/screener:
    get:
      summary: get-screener-handler
      description: 'Given a patient id, return all active (unscored) screeners for that patient.

        Filters the screeners and enriches the data per the `eden-screeners` athena

        config entry.

        Prepends any custom screeners from our dB.'
      tags:
      - grdn.routes.impl.screeners
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs/patient-id-params'
        required: true
        schema:
          type: string
          format: uuid
      - in: query
        name: funnel-id
        description: 'origin spec: grdn.specs/patient-id-params'
        required: false
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: getV2PatientByPatientIdScreener
      x-operation-id-source: derived
  /v2/patient/{patient-id}/screener-status:
    get:
      summary: get-screener-status-handler
      description: Gets all screeners completed by the patient, and filters the list based on screener-group.
      tags:
      - grdn.routes.impl.screeners
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs/get-screener-status-params'
        required: true
        schema:
          type: string
          format: uuid
      - in: query
        name: screener-groups
        description: 'origin spec: grdn.specs/get-screener-status-params'
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  screener-status:
                    type: array
                    items:
                      type: object
                      properties:
                        screener-group:
                          type: string
                        latest-version:
                          type: string
                        completed-version:
                          type: string
                      required:
                      - screener-group
                      - latest-version
                      - completed-version
                required:
                - screener-status
                title: grdn.specs.screeners/get-screener-status-response
      operationId: getV2PatientByPatientIdScreenerStatus
      x-operation-id-source: derived
  /v2/patient/{patient-id}/vax-location:
    get:
      summary: get-vax-location-handler
      description: Gets location from latest COVID vaccine survey response completed by the patient.
      tags:
      - grdn.routes.impl.screeners
      parameters:
      - in: path
        name: patient-id
        description: 'origin spec: grdn.specs/patient-id-params'
        required: true
        schema:
          type: string
          format: uuid
      - in: query
        name: funnel-id
        description: 'origin spec: grdn.specs/patient-id-params'
        required: false
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  location:
                    type: string
                required:
                - location
                title: grdn.specs.screeners/get-vax-location-response
      operationId: getV2PatientByPatientIdVaxLocation
      x-operation-id-source: derived
  /v2/screener-card:
    get:
      summary: get-screener-card-handler
      description: Given a screener ID return sorted question list
      tags:
      - grdn.routes.impl.screeners
      parameters:
      - in: query
        name: screener-response-id
        description: 'origin spec: grdn.specs/screener-card-response-params'
        required: true
        schema:
          type: string
          format: uuid
      - in: query
        name: covid-screener-id
        description: 'origin spec: grdn.specs/screener-card-response-params'
        required: true
        schema:
          type: string
          format: uuid
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema: {}
      operationId: getV2ScreenerCard
      x-operation-id-source: derived
