openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.brad API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.brad
  description: null
paths:
  /v2/brad/status:
    get:
      summary: get-status-handler
      description: Indicates BRAD state
      tags:
      - grdn.routes.impl.brad
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  state:
                    type: string
                    x-allOf:
                    - type: string
                    - x-anyOf:
                      - {}
                      - {}
                required:
                - state
                title: grdn.specs.brad/get-status-response
      operationId: getV2BradStatus
      x-operation-id-source: derived
  /v2/brad/status/active:
    put:
      summary: set-status-active-handler
      description: Sets BRAD state to active (enabled)
      tags:
      - grdn.routes.impl.brad
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                required:
                - success
                title: grdn.specs.brad/set-status-response
      operationId: putV2BradStatusActive
      x-operation-id-source: derived
  /v2/brad/status/inactive:
    put:
      summary: set-status-inactive-handler
      description: Sets BRAD state to inactive (disabled)
      tags:
      - grdn.routes.impl.brad
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                required:
                - success
                title: grdn.specs.brad/set-status-response
      operationId: putV2BradStatusInactive
      x-operation-id-source: derived
