openapi: 3.2.0
info:
  version: null
  title: Grdn.routes.impl.chat API
  description: Eden Health Inc. primary backend API service.
tags:
- name: grdn.routes.impl.chat
  description: null
paths:
  /v2/chats/summarize:
    post:
      summary: summarize-chat
      description: ''
      tags:
      - grdn.routes.impl.chat
      responses:
        default:
          description: Default success response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                required:
                - summary
                title: grdn.specs.chat/summarize-chat-handler-resp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient-id:
                  type: string
                  format: uuid
                start-time: {}
                end-time: {}
              required:
              - patient-id
              - start-time
              - end-time
              title: grdn.specs.chat/summarize-chat-handler-params
        description: 'origin spec: grdn.specs.chat/summarize-chat-handler-params'
      operationId: postV2ChatsSummarize
      x-operation-id-source: derived
